// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgqgxlZtwE3xfSZjmE_-seBcsjXYw690A',
    appId: '1:512490773695:web:b05337355b6f7398747a0a',
    messagingSenderId: '512490773695',
    projectId: 'certification-cources',
    authDomain: 'certification-cources.firebaseapp.com',
    storageBucket: 'certification-cources.appspot.com',
    measurementId: 'G-ELBDL3GKCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFxJSUdVZxnlj8ku4FxpuXpfxgmW0Gj3M',
    appId: '1:512490773695:android:04f3a217ad810e15747a0a',
    messagingSenderId: '512490773695',
    projectId: 'certification-cources',
    storageBucket: 'certification-cources.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8kt0Mv2d17oakxr3c-rYo1GYsIGpyUFc',
    appId: '1:512490773695:ios:a35dc679ecd63538747a0a',
    messagingSenderId: '512490773695',
    projectId: 'certification-cources',
    storageBucket: 'certification-cources.appspot.com',
    iosBundleId: 'com.example.certificationCources',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8kt0Mv2d17oakxr3c-rYo1GYsIGpyUFc',
    appId: '1:512490773695:ios:d39bde457e3a2f44747a0a',
    messagingSenderId: '512490773695',
    projectId: 'certification-cources',
    storageBucket: 'certification-cources.appspot.com',
    iosBundleId: 'com.example.certificationCources.RunnerTests',
  );
}
